connect:
  twitter:
    key: "JInLkOAb4c20sJYpatg"
    secret: "bJmZLu71qtzZUDFsqvcb1ID08QT4yt08kYISVbFvY"
    label: "Twitter"
  facebook:
    key: "246967045336612"
    secret: "80cbdb0f5a64c5ae299d3ab6a4dcc539"
    label: "Facebook"
    scope: "email, offline_access, user_work_history, user_location, user_hometown, read_stream"
  google:
    key: "my_key"
    secret: "my_secret"
    label: "Google"
  yahoo:
    key: "my_key"
    secret: "my_secret"
    label: "Yahoo"
  myspace:
    key: "4fd2d9671b24416db03311f27a78ab97"
    secret: "9f8976f2ce3c4c589d970cd6c21e14c2e5434f346f704f0eadd2318fe8d99be7"
  vimeo:
    key: "my_key"
    secret: "my_secret"
  linked_in:
    key: "i7zw7rjdks5n"
    secret: "zMu9y04KIUDZT5gI"
