connect:
  twitter:
    key: "JInLkOAb4c20sJYpatg"
    secret: "bJmZLu71qtzZUDFsqvcb1ID08QT4yt08kYISVbFvY"
    label: "Twitter"
  facebook:
    key: "176485969058177"
    secret: "d5883469ab10f4752067ea15b9aabf8d"
    label: "Facebook"
  google:
    key: "my_key"
    secret: "my_secret"
    label: "Google"
  yahoo:
    key: "my_key"
    secret: "my_secret"
    label: "Yahoo"
  myspace:
    key: "my_key"
    secret: "my_secret"
  vimeo:
    key: "my_key"
    secret: "my_secret"
  linked_in:
    key: "my_key"
    secret: "my_secret"
